export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_ACTIONS = [SIGN_UP_REQUEST, SIGN_UP_SUCCESS, SIGN_UP_FAILURE];

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_IN_ACTIONS = [LOG_IN_REQUEST, LOG_IN_SUCCESS, LOG_IN_FAILURE];

export const LOUNGE_ENTER_REQUEST = 'LOUNGE_ENTER_REQUEST';
export const LOUNGE_ENTER_SUCCESS = 'LOUNGE_ENTER_SUCCESS';
export const LOUNGE_ENTER_FAILURE = 'LOUNGE_ENTER_FAILURE';
export const LOUNGE_ENTER_ACTIONS = ['LOUNGE_ENTER_REQUEST', 'LOUNGE_ENTER_SUCCESS', 'LOUNGE_ENTER_FAILURE'];

export const INVITATION_SEND_REQUEST = 'INVITATION_SEND_REQUEST';
export const INVITATION_SEND_SUCCESS = 'INVITATION_SEND_SUCCESS';
export const INVITATION_SEND_FAILURE = 'INVITATION_SEND_FAILURE';
export const INVITATION_SEND_ACTIONS = ['INVITATION_SEND_REQUEST', 'INVITATION_SEND_SUCCESS', 'INVITATION_SEND_FAILURE'];

export const INVITATION_GET_REQUEST = 'INVITATION_GET_REQUEST';
export const INVITATION_GET_SUCCESS = 'INVITATION_GET_SUCCESS';
export const INVITATION_GET_FAILURE = 'INVITATION_GET_FAILURE';
export const INVITATION_GET_ACTIONS = ['INVITATION_GET_REQUEST', 'INVITATION_GET_SUCCESS', 'INVITATION_GET_FAILURE'];

export const INVITATION_ACCEPT_REQUEST = 'INVITATION_ACCEPT_REQUEST';
export const INVITATION_ACCEPT_SUCCESS = 'INVITATION_ACCEPT_SUCCESS';
export const INVITATION_ACCEPT_FAILURE = 'INVITATION_ACCEPT_FAILURE';
export const INVITATION_ACCEPT_ACTIONS = ['INVITATION_ACCEPT_REQUEST', 'INVITATION_ACCEPT_SUCCESS', 'INVITATION_ACCEPT_FAILURE'];

export const INVITATION_CANCEL_REQUEST = 'INVITATION_CANCEL_REQUEST';
export const INVITATION_CANCEL_SUCCESS = 'INVITATION_CANCEL_SUCCESS';
export const INVITATION_CANCEL_FAILURE = 'INVITATION_CANCEL_FAILURE';
export const INVITATION_CANCEL_ACTIONS = ['INVITATION_CANCEL_REQUEST', 'INVITATION_CANCEL_SUCCESS', 'INVITATION_CANCEL_FAILURE'];

export const INVITATION_REJECT_REQUEST = 'INVITATION_REJECT_REQUEST';
export const INVITATION_REJECT_SUCCESS = 'INVITATION_REJECT_SUCCESS';
export const INVITATION_REJECT_FAILURE = 'INVITATION_REJECT_FAILURE';
export const INVITATION_REJECT_ACTIONS = ['INVITATION_REJECT_REQUEST', 'INVITATION_REJECT_SUCCESS', 'INVITATION_REJECT_FAILURE'];


export const GAME_GET_REQUEST = 'GAME_GET_REQUEST';
export const GAME_GET_SUCCESS = 'GAME_GET_SUCCESS';
export const GAME_GET_FAILURE = 'GAME_GET_FAILURE';
export const GAME_GET_ACTIONS = ['GAME_GET_REQUEST', 'GAME_GET_SUCCESS', 'GAME_GET_FAILURE'];

export const ANSWER_REQUEST = 'ANSWER_REQUEST';
export const ANSWER_SUCCESS = 'ANSWER_SUCCESS';
export const ANSWER_FAILURE = 'ANSWER_FAILURE';
export const ANSWER_ACTIONS = ['ANSWER_REQUEST', 'ANSWER_SUCCESS', 'ANSWER_FAILURE'];

export const WS_USER_ENTERED_LOUNGE = 'WS_USER_ENTERED_LOUNGE';
export const WS_USER_LEFT_LOUNGE = 'WS_USER_LEFT_LOUNGE';
export const WS_INVITATION_RECEIVED = 'WS_INVITATION_RECEIVED';
export const WS_INVITATION_CANCELLED = 'WS_INVITATION_CANCELLED';
export const WS_INVITATION_ACCEPTED = 'WS_INVITATION_ACCEPTED';
export const WS_INVITATION_REJECTED = 'WS_INVITATION_REJECTED';
export const WS_ADVANCE_GAME = 'WS_ADVANCE_GAME';
export const WS_GAME_STATE_CHANGE = 'WS_GAME_STATE_CHANGE';

export const NUM_OF_QUESTIONS = 10;
export const QUESTION_TIMEOUT = 10;