export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_ACTIONS = ['REGISTER_REQUEST', 'REGISTER_SUCCESS', 'REGISTER_FAILURE'];

export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
export const AUTHENTICATE_ACTIONS = ['AUTHENTICATE_REQUEST', 'AUTHENTICATE_SUCCESS', 'AUTHENTICATE_FAILURE'];

export const LOUNGE_ENTER_REQUEST = 'LOUNGE_ENTER_REQUEST';
export const LOUNGE_ENTER_SUCCESS = 'LOUNGE_ENTER_SUCCESS';
export const LOUNGE_ENTER_FAILURE = 'LOUNGE_ENTER_FAILURE';
export const LOUNGE_ENTER_ACTIONS = ['LOUNGE_ENTER_REQUEST', 'LOUNGE_ENTER_SUCCESS', 'LOUNGE_ENTER_FAILURE'];

export const INVITATION_SEND_REQUEST = 'INVITATION_SEND_REQUEST';
export const INVITATION_SEND_SUCCESS = 'INVITATION_SEND_SUCCESS';
export const INVITATION_SEND_FAILURE = 'INVITATION_SEND_FAILURE';
export const INVITATION_SEND_ACTIONS = ['INVITATION_SEND_REQUEST', 'INVITATION_SEND_SUCCESS', 'INVITATION_SEND_FAILURE'];

export const INVITATION_GET_REQUEST = 'INVITATION_GET_REQUEST';
export const INVITATION_GET_SUCCESS = 'INVITATION_GET_SUCCESS';
export const INVITATION_GET_FAILURE = 'INVITATION_GET_FAILURE';
export const INVITATION_GET_ACTIONS = ['INVITATION_GET_REQUEST', 'INVITATION_GET_SUCCESS', 'INVITATION_GET_FAILURE'];

export const INVITATION_ACCEPT_REQUEST = 'INVITATION_ACCEPT_REQUEST';
export const INVITATION_ACCEPT_SUCCESS = 'INVITATION_ACCEPT_SUCCESS';
export const INVITATION_ACCEPT_FAILURE = 'INVITATION_ACCEPT_FAILURE';
export const INVITATION_ACCEPT_ACTIONS = ['INVITATION_ACCEPT_REQUEST', 'INVITATION_ACCEPT_SUCCESS', 'INVITATION_ACCEPT_FAILURE'];

export const GAME_GET_REQUEST = 'GAME_GET_REQUEST';
export const GAME_GET_SUCCESS = 'GAME_GET_SUCCESS';
export const GAME_GET_FAILURE = 'GAME_GET_FAILURE';
export const GAME_GET_ACTIONS = ['GAME_GET_REQUEST', 'GAME_GET_SUCCESS', 'GAME_GET_FAILURE'];

export const ANSWER_REQUEST = 'ANSWER_REQUEST';
export const ANSWER_SUCCESS = 'ANSWER_SUCCESS';
export const ANSWER_FAILURE = 'ANSWER_FAILURE';
export const ANSWER_ACTIONS = ['ANSWER_REQUEST', 'ANSWER_SUCCESS', 'ANSWER_FAILURE'];

export const WS_USER_ENTERED_LOUNGE = 'WS_USER_ENTERED_LOUNGE';